/* Copyright (c) 2025 Otto Link. Distributed under the terms of the GNU General
 * Public License. The full license is in the file LICENSE, distributed with
 * this software. */
#include <cstddef>
#include <fstream>
#include <map>
#include <string>
#include <vector>

#include "highmap/internal/validation.hpp"
#include "highmap/logger.hpp"

namespace hmap
{

void export_points_to_ply(
    const std::string                               &fname,
    const std::vector<float>                        &x,
    const std::vector<float>                        &y,
    const std::vector<float>                        &z,
    const std::map<std::string, std::vector<float>> &custom_fields)
{
  if (!validate_non_empty(x, "x") || !validate_non_empty(y, "y") ||
      !validate_non_empty(z, "z"))
  {
    return;
  }

  // check input vector sizes
  if (x.size() != y.size() || x.size() != z.size())
  {
    hmap::log::warn(
        "x, y, and z vectors must have the same size (x: {}, y: {}, z: {})",
        x.size(),
        y.size(),
        z.size());
    return;
  }

  std::size_t n_points = x.size();
  for (const auto &[name, values] : custom_fields)
  {
    if (values.size() != n_points)
    {
      hmap::log::warn("custom field {} has size {} but expected {}.",
                      name,
                      values.size(),
                      n_points);
      return;
    }
  }

  std::ofstream out(fname);
  if (!out.is_open())
  {
    hmap::log::warn("could not open file {} for writing.", fname);
    return;
  }

  // write header
  out << "ply\n";
  out << "format ascii 1.0\n";
  out << "comment file automatically generated by HighMap "
         "https://github.com/otto-link/HighMap\n";
  out << "element vertex " << n_points << "\n";
  out << "property float x\n";
  out << "property float y\n";
  out << "property float z\n";
  for (const auto &[name, _] : custom_fields)
    out << "property float " << name << "\n";
  out << "element face 0\n";
  out << "property list uchar int vertex_index\n";
  out << "end_header\n";

  // write vertex data
  for (std::size_t i = 0; i < n_points; ++i)
  {
    out << x[i] << " " << y[i] << " " << z[i];
    for (const auto &[_, values] : custom_fields)
      out << " " << values[i];
    out << "\n";
  }
}

} // namespace hmap
